services:
  - type: web
    name: jose-portafolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn JosePortafolio.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "jose-portafolio.onrender.com"
